version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami1:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  whoami2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  whoami3:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local